# Generated by Django 4.1.2 on 2024-07-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0002_producto_nombre_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagen_restaurante',
            field=models.ImageField(null=True, upload_to='alimentacion'),
        ),
    ]
