# Generated by Django 4.1.2 on 2024-07-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0003_restaurante_imagen_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(null=True, upload_to='alimentacion'),
        ),
    ]
