# Generated by Django 4.1.2 on 2024-07-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0004_producto_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_producto',
            field=models.FloatField(default=1),
        ),
    ]
