# Generated by Django 4.1.2 on 2024-07-04 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0006_alter_producto_precio_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
