# Generated by Django 4.1.2 on 2024-07-06 00:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='diariosemanal',
            fields=[
                ('id_diariosemanal', models.AutoField(db_column='idCategorias', primary_key=True, serialize=False)),
                ('nombre_diariosemanal', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'db_table': 'diariosemanal',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='menusemanal_prod',
            field=models.ForeignKey(db_column='idDiariosemanal', default=1, on_delete=django.db.models.deletion.CASCADE, to='alimentacion.diariosemanal'),
        ),
    ]
