# Generated by Django 4.1.2 on 2024-07-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0008_diariosemanal_producto_menusemanal_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariosemanal',
            name='id_diariosemanal',
            field=models.AutoField(db_column='idDiariosemanal', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='menusemanal_prod',
            field=models.ForeignKey(db_column='idDiariosemanal', on_delete=django.db.models.deletion.CASCADE, to='alimentacion.diariosemanal'),
        ),
    ]
