# Generated by Django 4.1.2 on 2024-07-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0011_usuario_is_active_usuario_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
