# Generated by Django 4.1.2 on 2024-07-08 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0014_alter_producto_precio_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
