# Generated by Django 4.1.2 on 2024-07-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0019_reclamo_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comentario_Feedback',
            new_name='comentario_feedback',
        ),
    ]
